# Generated by Django 6.0.7 on 2026-08-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('feature_project', 'Can feature project')]},
        ),
    ]
